package com.example.shurufa.input

import android.content.Context
import android.util.Log
import java.io.BufferedReader
import java.io.InputStreamReader

class PinyinConverter(private val context: Context) {
    
    private val pinyinMap = mutableMapOf<String, MutableList<String>>()
    private val zhCNWords = mutableMapOf<String, MutableList<String>>()
    
    companion object {
        private const val TAG = "PinyinConverter"
        
        private val PINYIN_DICT = mapOf(
            "a" to "啊阿吖嗄腌锕",
            "ai" to "爱矮挨哎碍癌艾唉矮蔼隘埃癌艾",
            "an" to "安案按暗岸俺鞍氨胺庵广",
            "ang" to "昂昂盎",
            "ao" to "奥傲熬凹敖澳坳拗嗷岙熬",
            "ba" to "把八巴拔罢爸霸扒叭芭笆疤跋巴",
            "bai" to "百白摆败拜柏伯",
            "ban" to "办半班板般颁斑搬扮瓣拌",
            "bang" to "帮邦棒榜绑傍磅蚌",
            "bao" to "报保包宝抱暴薄爆炮剥饱保",
            "bei" to "被北备背贝杯倍杯辈悲",
            "ben" to "本奔苯笨",
            "beng" to "蹦崩绷蹦",
            "bi" to "比笔闭鼻必毕避碧毙毖",
            "bian" to "边便变编遍辩贬辨辫",
            "biao" to "表标彪膘飘",
            "bie" to "别憋瘪",
            "bin" to "宾滨彬彬斌缤濒",
            "bing" to "并病冰丙柄饼",
            "bo" to "博拨播搏薄伯勃波帛般",
            "bu" to "不布步补埠部捕怖",
            "ca" to "擦拆",
            "cai" to "才采彩材菜财裁",
            "can" to "参餐残灿惨",
            "cang" to "藏仓沧苍舱",
            "cao" to "草操曹糙",
            "ce" to "测策册侧厕恻",
            "ceng" to "层曾蹭",
            "cha" to "查茶差插察茬碴",
            "chai" to "拆柴钗",
            "chan" to "产阐颤铲谗馋蝉",
            "chang" to "长场常唱厂昌肠偿畅",
            "chao" to "超朝潮炒抄吵嘲",
            "che" to "车彻扯澈",
            "chen" to "称陈沉晨衬趁",
            "cheng" to "成城呈承程惩撑诚",
            "chi" to "吃尺赤池迟驰耻齿持",
            "chong" to "重充冲虫崇宠",
            "chou" to "抽愁丑臭仇稠绸",
            "chu" to "出处初础除储畜触",
            "chuai" to "揣",
            "chuan" to "传船串川穿",
            "chuang" to "创床闯",
            "chui" to "吹垂炊锤",
            "chun" to "春纯淳唇醇",
            "chuo" to "戳绰",
            "ci" to "此次词辞刺瓷慈磁",
            "cong" to "从丛聪葱囱",
            "cou" to "凑",
            "cu" to "粗促簇醋",
            "cuan" to "窜攒篡窜",
            "cui" to "催脆崔萃",
            "cun" to "村寸存",
            "cuo" to "错措搓挫",
            "da" to "大达答打",
            "dai" to "带代待袋呆带逮",
            "dan" to "但单担蛋淡弹胆",
            "dang" to "当党档挡",
            "dao" to "到道导倒刀岛捣",
            "de" to "的得",
            "deng" to "等邓凳瞪",
            "di" to "地底弟低滴迪敌狄",
            "dian" to "点店电殿淀惦奠",
            "diao" to "掉调吊雕钓",
            "die" to "爹跌叠谍碟",
            "ding" to "定订顶丁钉叮",
            "diu" to "丢",
            "dong" to "动东冬懂洞冻",
            "dou" to "都斗豆逗读",
            "du" to "度读独毒渡杜堵",
            "duan" to "段短断端锻",
            "dui" to "对队堆兑",
            "dun" to "吨顿蹲钝盾",
            "duo" to "多夺朵踱舵",
            "e" to "额恶饿扼遏鄂",
            "en" to "恩",
            "er" to "而二儿耳尔饵",
            "fa" to "发法罚伐",
            "fan" to "反范翻犯凡帆返",
            "fang" to "方放房防访仿纺",
            "fei" to "非飞费肥废沸",
            "fen" to "分份粉纷奋愤粪",
            "feng" to "风封峰锋丰凤蜂",
            "fo" to "佛",
            "fou" to "否",
            "fu" to "服福副付父复附扶",
            "ga" to "噶嘎",
            "gai" to "该改盖钙",
            "gan" to "干赶感敢甘肝杆",
            "gang" to "刚钢港岗纲肛",
            "gao" to "高告稿糕",
            "ge" to "个各歌哥格隔革",
            "gei" to "给",
            "gen" to "根跟",
            "geng" to "更耕颈羹",
            "gong" to "工公功共供宫攻",
            "gou" to "够狗购构钩",
            "gu" to "古股故顾固估鼓",
            "gua" to "挂刮瓜寡卦",
            "guai" to "怪乖拐",
            "guan" to "关官管观馆惯",
            "guang" to "光广逛",
            "gui" to "规贵归鬼轨桂柜",
            "gun" to "棍滚辊",
            "guo" to "过国果锅",
            "ha" to "哈",
            "hai" to "还海害骸",
            "han" to "汉喊寒含韩罕函",
            "hang" to "行航巷",
            "hao" to "好号浩豪毫皓",
            "he" to "和河何合盒喝贺",
            "hei" to "黑嘿",
            "hen" to "很狠恨",
            "heng" to "横恒哼",
            "hong" to "红洪宏虹鸿哄",
            "hou" to "后候厚侯猴",
            "hu" to "户互湖胡虎糊核",
            "hua" to "话华化花画划",
            "huai" to "坏淮槐",
            "huan" to "还换环缓唤 환欢",
            "huang" to "黄慌晃荒谎",
            "hui" to "会回汇灰毁辉惠",
            "hun" to "混婚魂浑昏",
            "huo" to "或活火获货祸霍",
            "ji" to "及机级即极几济继",
            "jia" to "家加假价架甲嘉",
            "jian" to "间建见件键监简减",
            "jiang" to "将讲江奖蒋浆",
            "jiao" to "叫脚交较教焦骄",
            "jie" to "她节解姐借街皆揭",
            "jin" to "金进今近仅尽紧",
            "jing" to "经京精竟静惊景",
            "jiong" to "窘炯",
            "jiu" to "就九酒久救旧舅",
            "ju" to "举据局聚巨居菊",
            "juan" to "卷捐圈眷",
            "jue" to "决绝角觉掘",
            "jun" to "军君均俊菌",
            "ka" to "卡咖喀",
            "kai" to "开揩凯慨",
            "kan" to "看刊坎砍勘",
            "kang" to "抗康慷",
            "kao" to "考烤靠",
            "ke" to "可科课克刻客",
            "ken" to "肯恳啃",
            "keng" to "坑吭",
            "kong" to "空控孔恐",
            "kou" to "口扣抠",
            "ku" to "苦库哭酷",
            "kua" to "跨夸垮挎",
            "kuai" to "快块会计",
            "kuan" to "宽款",
            "kuang" to "况框矿狂",
            "kui" to "亏愧溃葵",
            "kun" to "困昆坤",
            "kuo" to "扩阔廓",
            "la" to "拉啦辣蜡腊",
            "lai" to "来赖莱",
            "lan" to "兰蓝拦篮烂滥",
            "lang" to "浪郎狼廊朗",
            "lao" to "老劳姥捞烙",
            "le" to "了乐勒",
            "lei" to "类累雷泪磊",
            "leng" to "冷楞",
            "li" to "里力立李历例利",
            "lia" to "俩",
            "lian" to "连联脸练恋链莲",
            "liang" to "两量亮粮凉梁",
            "liao" to "了料疗辽聊",
            "lie" to "列烈猎劣",
            "lin" to "林临邻凛吝",
            "ling" to "另零领龄灵凌",
            "liu" to "六流留刘硫",
            "long" to "龙隆笼拢",
            "lou" to "楼搂娄漏",
            "lu" to "路露陆卢鲁录",
            "lv" to "律旅绿率虑",
            "luan" to "乱卵",
            "lue" to "略掠",
            "lun" to "论轮伦",
            "luo" to "罗洛落络螺",
            "ma" to "妈马吗嘛麻骂",
            "mai" to "买卖麦迈",
            "man" to "满慢漫曼",
            "mang" to "忙芒盲茫",
            "mao" to "毛冒帽贸猫茅",
            "me" to "么",
            "mei" to "没每美妹梅媒",
            "men" to "们门闷",
            "meng" to "梦盟猛蒙锰",
            "mi" to "米密迷蜜觅",
            "mian" to "面棉眠免缅",
            "miao" to "秒苗描妙庙",
            "mie" to "灭蔑",
            "min" to "民敏闽抿",
            "ming" to "明名命鸣",
            "miu" to "谬",
            "mo" to "莫末模摸墨默",
            "mou" to "某牟眸",
            "mu" to "目母木幕墓慕",
            "na" to "那拿哪纳娜",
            "nai" to "乃奶耐奈",
            "nan" to "南男难",
            "nang" to "囊",
            "nao" to "脑闹恼",
            "ne" to "呢哪",
            "nei" to "内",
            "nen" to "嫩",
            "neng" to "能",
            "ni" to "你泥尼拟逆",
            "nian" to "年念捻",
            "niang" to "娘",
            "niao" to "鸟尿",
            "nie" to "捏聂孽",
            "nin" to "您",
            "ning" to "宁凝拧",
            "niu" to "牛扭纽",
            "nong" to "农浓弄",
            "nu" to "努奴怒",
            "nv" to "女",
            "nuan" to "暖",
            "nue" to "虐疟",
            "nuo" to "诺挪懦",
            "o" to "哦噢",
            "ou" to "欧偶呕",
            "pa" to "怕爬趴帕",
            "pai" to "派排拍牌",
            "pan" to "盘判叛畔潘",
            "pang" to "旁胖庞",
            "pao" to "跑炮泡刨",
            "pei" to "配陪培赔佩",
            "pen" to "喷盆",
            "peng" to "朋碰彭棚蓬",
            "pi" to "批皮披疲匹屁僻",
            "pian" to "片偏篇骗",
            "piao" to "票飘漂",
            "pie" to "撇瞥",
            "pin" to "品贫拼频",
            "ping" to "平凭评屏乒",
            "po" to "破迫坡泼颇",
            "pou" to "剖",
            "pu" to "普扑铺葡蒲",
            "qi" to "其起期七企气器",
            "qia" to "恰洽掐",
            "qian" to "前千签潜钱浅欠",
            "qiang" to "强墙抢腔",
            "qiao" to "桥乔巧敲悄",
            "qie" to "且切窃怯",
            "qin" to "亲琴侵秦勤",
            "qing" to "请青清轻情晴",
            "qiong" to "穷琼",
            "qiu" to "求球秋丘",
            "qu" to "区去取曲趣屈驱",
            "quan" to "全权圈劝泉",
            "que" to "却缺确雀",
            "qun" to "群裙",
            "ran" to "然燃染",
            "rang" to "让嚷壤",
            "rao" to "绕饶",
            "re" to "热惹",
            "ren" to "人认任仁刃",
            "reng" to "扔",
            "ri" to "日",
            "rong" to "容绒融荣冗",
            "rou" to "肉揉柔",
            "ru" to "如入儒乳",
            "ruan" to "软阮",
            "rui" to "瑞锐",
            "run" to "润",
            "ruo" to "若弱",
            "sa" to "撒洒",
            "sai" to "赛塞",
            "san" to "三散伞",
            "sang" to "桑嗓丧",
            "sao" to "扫嫂骚",
            "se" to "色涩瑟",
            "sen" to "森",
            "seng" to "僧",
            "sha" to "沙杀啥傻厦",
            "shai" to "晒筛",
            "shan" to "山闪善扇杉",
            "shang" to "上商伤尚",
            "shao" to "少绍烧稍哨",
            "she" to "社设舌射涉舍",
            "shen" to "身神深什沈审",
            "sheng" to "生声省胜圣",
            "shi" to "是时十事世市式",
            "shou" to "手首收受守",
            "shu" to "书树数属术述",
            "shua" to "刷耍",
            "shuai" to "摔帅率",
            "shuan" to "栓拴",
            "shuang" to "双爽",
            "shui" to "水税睡",
            "shun" to "顺瞬",
            "shuo" to "说硕朔",
            "si" to "四思死丝司私",
            "song" to "送松宋耸讼",
            "sou" to "搜艘",
            "su" to "速素诉苏俗宿",
            "suan" to "算酸蒜",
            "sui" to "岁随碎穗遂",
            "sun" to "孙损笋",
            "suo" to "所索缩锁",
            "ta" to "他她它踏塔塌",
            "tai" to "太台态抬泰",
            "tan" to "谈弹坦叹探贪",
            "tang" to "糖汤唐堂塘膛",
            "tao" to "讨套逃桃淘",
            "te" to "特",
            "teng" to "疼腾藤",
            "ti" to "体题提踢替",
            "tian" to "天田添填甜",
            "tiao" to "条调跳挑",
            "tie" to "铁帖贴",
            "ting" to "听停庭挺",
            "tong" to "同通痛统铜童",
            "tou" to "头投透",
            "tu" to "土图途突秃",
            "tuan" to "团湍",
            "tui" to "推腿退",
            "tun" to "吞屯臀",
            "tuo" to "托脱拓拖陀",
            "wa" to "挖瓦蛙娃哇",
            "wai" to "外歪",
            "wan" to "完万晚玩碗弯",
            "wang" to "往王网望忘亡",
            "wei" to "为位未围伟卫",
            "wen" to "文问闻温稳",
            "weng" to "嗡翁",
            "wo" to "我握卧窝",
            "wu" to "无五物午武务",
            "xi" to "西系息希习细喜",
            "xia" to "下夏吓侠狭霞",
            "xian" to "先现线县显险献",
            "xiang" to "想向相象香乡响",
            "xiao" to "小效校笑消肖",
            "xie" to "些写谢斜鞋",
            "xin" to "心新辛欣信",
            "xing" to "行性星兴姓醒",
            "xiong" to "兄熊胸雄",
            "xiu" to "修秀休羞",
            "xu" to "需许续需虚",
            "xuan" to "选宣旋悬",
            "xue" to "学雪血削",
            "xun" to "讯迅寻巡循",
            "ya" to "压呀牙芽崖哑",
            "yan" to "研眼严言沿演",
            "yang" to "样阳养羊扬洋",
            "yao" to "要药邀摇耀",
            "ye" to "也页业夜叶",
            "yi" to "一以已意义亿",
            "yin" to "因银音引印饮",
            "ying" to "应影营迎赢英",
            "yo" to "哟",
            "yong" to "用永勇涌泳",
            "you" to "有由又友右优",
            "yu" to "于语与予欲宇",
            "yuan" to "元原员圆园源",
            "yue" to "月越约乐跃",
            "yun" to "云运允孕韵",
            "za" to "杂咱砸",
            "zai" to "在再灾载",
            "zan" to "咱暂赞",
            "zang" to "脏葬",
            "zao" to "早造遭枣糟",
            "ze" to "则责择泽",
            "zei" to "贼",
            "zen" to "怎",
            "zeng" to "曾增赠",
            "zha" to "炸扎渣闸",
            "zhai" to "宅债寨窄",
            "zhan" to "站战占湛盏",
            "zhang" to "长张章掌涨障",
            "zhao" to "找着照赵召",
            "zhe" to "这者着折哲",
            "zhen" to "真镇针震振",
            "zheng" to "正政证争整郑",
            "zhi" to "之知只直治纸",
            "zhong" to "中种众终重",
            "zhou" to "周州洲粥轴",
            "zhu" to "主住注助祝著",
            "zhua" to "抓爪",
            "zhuai" to "拽",
            "zhuan" to "转专砖赚传",
            "zhuang" to "装庄壮撞",
            "zhui" to "追坠缀",
            "zhun" to "准",
            "zhuo" to "桌捉卓灼浊",
            "zi" to "子自字资紫",
            "zong" to "总宗综纵",
            "zou" to "走奏揍",
            "zu" to "组族足阻租",
            "zuan" to "钻赚",
            "zui" to "最嘴罪",
            "zun" to "尊遵",
            "zuo" to "作做坐左座",
            "ch" to "吃出车称冲",
            "sh" to "是时沙书",
            "zh" to "之知中主",
            "ai" to "爱挨埃哎唉",
            "ei" to "诶诶诶诶",
            "ui" to "对堆队追",
            "ao" to "奥澳傲凹",
            "ou" to "欧偶呕",
            "iu" to "六流刘",
            "ie" to "也叶解",
            "ve" to "月约乐",
            "er" to "而二儿耳",
            "an" to "安按案暗",
            "en" to "恩嗯摁",
            "in" to "音引印",
            "un" to "云运温",
            "ang" to "昂昂盎",
            "eng" to "鞥亨",
            "ing" to "英应影",
            "ong" to "中龙东"
        )
    }
    
    init {
        Log.d(TAG, "PinyinConverter initialized")
    }
    
    fun getCandidates(pinyin: String): List<String> {
        if (pinyin.isEmpty()) return emptyList()
        
        val normalizedPinyin = normalizePinyin(pinyin)
        
        val candidates = mutableListOf<String>()
        
        pinyinMap[normalizedPinyin]?.let {
            candidates.addAll(it)
        }
        
        if (pinyinMap[normalizedPinyin] == null && PINYIN_DICT[normalizedPinyin] != null) {
            candidates.addAll(PINYIN_DICT[normalizedPinyin]!!.map { it.toString() })
        }
        
        val combinedCandidates = mutableListOf<String>()
        
        val firstMatch = PINYIN_DICT.entries.find { 
            normalizedPinyin.startsWith(it.key) || it.key.startsWith(normalizedPinyin) 
        }
        
        if (firstMatch != null && candidates.size < 9) {
            for (char in firstMatch.value) {
                val charStr = char.toString()
                if (!candidates.contains(charStr)) {
                    combinedCandidates.add(charStr)
                }
            }
        }
        
        val finalCandidates = candidates.take(9).toMutableList()
        
        combinedCandidates.forEach { c ->
            if (finalCandidates.size < 9 && !finalCandidates.contains(c)) {
                finalCandidates.add(c)
            }
        }
        
        return finalCandidates.take(9)
    }
    
    private fun normalizePinyin(pinyin: String): String {
        return pinyin.lowercase()
            .replace("ā", "a").replace("á", "a").replace("ǎ", "a").replace("à", "a")
            .replace("ē", "e").replace("é", "e").replace("ě", "e").replace("è", "e")
            .replace("ī", "i").replace("í", "i").replace("ǐ", "i").replace("ì", "i")
            .replace("ō", "o").replace("ó", "o").replace("ǒ", "o").replace("ò", "o")
            .replace("ū", "u").replace("ú", "u").replace("ǔ", "u").replace("ù", "u")
            .replace("ǖ", "v").replace("ǘ", "v").replace("ǚ", "v").replace("ǜ", "v")
            .replace("ü", "v")
    }
}
